name: Build HinoGram
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # CORRECTION ICI : On ajoute les options pour tout télécharger
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Télécharge les sous-dossiers (le moteur)
          fetch-depth: 0         # Récupère tout l'historique (nécessaire pour la version)
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        # Ajout de --scan pour avoir un lien de débogage si jamais ça recrache
        run: ./gradlew assembleFossDebug --stacktrace --scan

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hino-Gram-Debug
          path: TMessagesProj/build/outputs/apk/foss/debug/*.apk